spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/springtask"
    username: postgres
    password: postgres
  flyway:
    user: postgres
    password: postgres
