CREATE TABLE weather(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    city VARCHAR NOT NULL,
    temperature FLOAT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
)
